paths:
 urdf: "assets/puzzlebot/urdf/puzzlebot.urdf"
 usd_output: "simulation/simulation_std/generated_usd/puzzlebot.usd" 

robot:
 prim_path: "/World/puzzlebot"
 articulation_path: "/World/puzzlebot/base_footprint"
 left_wheel_joint: "base_to_left_wheel"
 right_wheel_joint: "base_to_right_wheel"
 wheel_radius: 0.05
 wheel_base: 0.18

sensors:
  camera:
    width: 320
    height: 240
    focal_length: 30.4
    horizontal_aperture: 36.8
    vertical_aperture: 27.6
    clipping_near: 0.05
    clipping_far: 50.0
    resolution: [360, 180]
    topic: "camera/image_raw"
    frame_id: "camera_color_optical_frame"
  lidar:
    config: "RPLIDAR_S2E"
    topic: "scan"
    frame_id: "lidar_link"

ros2:
  graph_path: "/World/ActionGraph/ROS2"
  use_domain_id_env_var: true
  topics:
    odom: "odom"
    joint_states: "joint_states"
    cmd_vel: "cmd_vel"
    clock: "clock"

world:
 stage_path: "worlds/puzz_scene.usd"
