zones:
  inspect:
    x: 1.2
    y: 0.6
    yaw: 1.5

  dropoff:
    x: 3.0
    y: 2.0
    yaw: 1.57
    
  home:
    x: 1.0
    y: 1.0
    yaw: 0.0

  popsi:
    x: 3.5
    y: 4.1
    yaw: 0.0

  emezon:
    x: 1.0
    y: 1.0
    yaw: 0.0

