zones:
  inspect:
    x: 1.0
    y: 3.3
    yaw: 3.14

  inspect2:
    x: 1.0
    y: 2.0
    yaw: 3.14

  center:
    x: 1.8
    y: 1.9
    yaw: 0.0

  center2:
    x: 2.1
    y: 1.9
    yaw: 0.0

  home:
    x: 1.15
    y: 1.7
    yaw: 1.5

  Emezon:
    x: 4.2
    y: 2.5
    yaw: -0.01

  Wolmar:
    x: 4.2
    y: 3.2
    yaw: -0.01

  Wolmar1:
    x: 4.15
    y: 3.2
    yaw: -0.01

  Wolmar2:
    x: 4.30
    y: 3.2
    yaw: -0.01

  Popsi:
    x: 4.2
    y: 2.0
    yaw: -0.01

  dropoff:
    x: 4.2
    y: 2.0
    yaw: 0.0



