zones:
  inspect:
    x: 0.8
    y: 2.5
    yaw: 3.14

  center:
    x: 1.8
    y: 1.9
    yaw: 0.0

  home:
    x: 1.15
    y: 1.7
    yaw: 1.5

  Emezon:
    x: 4.1
    y: 2.8
    yaw: 0.0

  Wolmar:
    x: 4.1
    y: 2.35
    yaw: 0.0

  Popsi:
    x: 4.1
    y: 1.8
    yaw: 0.0

  dropoff:
    x: 4.2
    y: 2.0
    yaw: 0.0



