path_trees:
    main_tree: trees/main_tree.xml
    docking_tree: trees/docking.xml
    debug_tree: trees/debug_tree.xml
    debug_docking: trees/docking_debug.xml
    main_qr: trees/main_qr.xml
    voice_tree: trees/bt_command.xml
