services:
  puzzlebot:
    build:
      context: ..
      dockerfile: docker/main/Dockerfile
    container_name: puzzlebot
    network_mode: host
    environment: 
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - NVIDIA_VISIBLE_DEVICES=all   
      - NVIDIA_DRIVER_CAPABILITIES=all      
      - LIBGL_ALWAYS_SOFTWARE=0
      - QT_X11_NO_MITSHM=1
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ws/fastdds_no_shm.xml
    devices:
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    group_add:
      - audio 
      - video 
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../src:/ws/src
      - ./fastdds_no_shm.xml:/ws/fastdds_no_shm.xml
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    restart: unless-stopped

  puzzlebot_cuda:
    build:
      context: ..
      dockerfile: docker/main_cuda/Dockerfile
    container_name: puzzlebot_cuda
    network_mode: host
    environment: 
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - NVIDIA_VISIBLE_DEVICES=all   
      - NVIDIA_DRIVER_CAPABILITIES=all      
      - LIBGL_ALWAYS_SOFTWARE=0
      - QT_X11_NO_MITSHM=1
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ws/fastdds_no_shm.xml
    devices:
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    group_add:
      - audio 
      - video 
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../src:/ws/src
      - ../isaac_sim:/ws/isaac_sim
      - ./fastdds_no_shm.xml:/ws/fastdds_no_shm.xml
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    restart: unless-stopped