services:

  puzzlebot: #main service(launches the bringup launch)
    build:
      context: .. #root of project
      dockerfile: docker/main/Dockerfile

    container_name: puzzlebot

    network_mode: host

    environment: 
      #- ROS_DOMAIN_ID=100
      - ROS_DOMAIN_ID=0 #when using jetson 
      - DISPLAY=${DISPLAY} #in case needing GUI
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - NVIDIA_VISIBLE_DEVICES=all   
      - NVIDIA_DRIVER_CAPABILITIES=all      
      - LIBGL_ALWAYS_SOFTWARE=0 
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ws/fastdds_no_shm.xml

    devices:
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0 
      - /dev/video0:/dev/video1 

    group_add:
      - audio 
      - video 
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ../src:/ws/src
      - ./fastdds_no_shm.xml:/ws/fastdds_no_shm.xml
      - /tmp/.X11-unix:/tmp/.X11-unix  # GUI

    
    stdin_open: true
    tty: true
    restart: unless-stopped


