robot:
 wheel_radius: 0.051
 wheel_base: 0.19

usd:
 stage_path: "../worlds/world.usd"
 robot_path: "/World/robot/"

joints:
  left:  "/World/robot/puzzlebot_v2/joints/base_to_left_wheel"
  right: "/World/robot/puzzlebot_v2/joints/base_to_right_wheel"

ros2:
 topics: 
  cmd_vel: "/cmd_vel"
  odom: "/odom"
  scan: "/scan"
  image: /camera/image_raw

sensors:
 lidar:
  frequency: 10.0

 camera:
  width: 320
  height: 160
  frequency: 15